In [1]:
import pandas as pd
import numpy as np
import seaborn as sns #Data Visualiation
import matplotlib.pyplot as plt #Data Visualiation
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, mean_squared_error, classification_report, confusion_matrix

In [3]:
from google.colab import drive                    # Mounting drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
data = pd.read_csv('/content/drive/MyDrive/emotions.csv')

In [5]:
data

# mean_0_a  mean_1_a  mean_2_a  mean_3_a  mean_4_a  mean_d_0_a  \
0          4.620      30.3    -356.0     15.60      26.3       1.070   
1         28.800      33.1      32.0     25.80      22.8       6.550   
2          8.900      29.4    -416.0     16.70      23.7      79.900   
3         14.900      31.6    -143.0     19.80      24.3      -0.584   
4         28.300      31.3      45.2     27.30      24.5      34.800   
...          ...       ...       ...       ...       ...         ...   
2127      32.400      32.2      32.2     30.80      23.4       1.640   
2128      16.300      31.3    -284.0     14.30      23.9       4.200   
2129      -0.547      28.3    -259.0     15.80      26.7       9.080   
2130      16.800      19.9    -288.0      8.34      26.0       2.460   
2131      27.000      32.0      31.8     25.00      28.9       4.990   

      mean_d_1_a  mean_d_2_a  mean_d_3_a  mean_d_4_a  ...  fft_741_b  \
0          0.411     -15.700       2.060        3.15  ...      23.50   
1          1.680       2.880       3.830       -4.82  ...     -23.30   
2          3.360      90.200      89.900        2.03  ...     462.00   
3         -0.284       8.820       2.300       -1.97  ...     299.00   
4         -5.790       3.060      41.400        5.52  ...      12.00   
...          ...         ...         ...         ...  ...        ...   
2127      -2.030       0.647      -0.121       -1.10  ...     -21.70   
2128       1.090       4.460       4.720        6.63  ...     594.00   
2129       6.900      12.700       2.030        4.64  ...     370.00   
2130       1.580     -16.000       1.690        4.74  ...     124.00   
2131       1.950       6.210       3.490       -3.51  ...       1.95   

      fft_742_b  fft_743_b  fft_744_b  fft_745_b  fft_746_b  fft_747_b  \
0        20.300     20.300      23.50     -215.0     280.00    -162.00   
1       -21.800    -21.800     -23.30      182.0       2.57     -31.60   
2      -233.000   -233.000     462.00     -267.0     281.00    -148.00   
3      -243.000   -243.000     299.00      132.0     -12.40       9.53   
4        38.100     38.100      12.00      119.0     -17.60      23.90   
...         ...        ...        ...        ...        ...        ...   
2127      0.218      0.218     -21.70       95.2     -19.90      47.20   
2128   -324.000   -324.000     594.00      -35.5     142.00     -59.80   
2129   -160.000   -160.000     370.00      408.0    -169.00     -10.50   
2130    -27.600    -27.600     124.00     -656.0     552.00    -271.00   
2131      1.810      1.810       1.95      110.0      -6.71      22.80   

      fft_748_b  fft_749_b     label  
0       -162.00     280.00  NEGATIVE  
1        -31.60       2.57   NEUTRAL  
2       -148.00     281.00  POSITIVE  
3          9.53     -12.40  POSITIVE  
4         23.90     -17.60   NEUTRAL  
...         ...        ...       ...  
2127      47.20     -19.90   NEUTRAL  
2128     -59.80     142.00  POSITIVE  
2129     -10.50    -169.00  NEGATIVE  
2130    -271.00     552.00  NEGATIVE  
2131      22.80      -6.71   NEUTRAL  

[2132 rows x 2549 columns]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2132 entries, 0 to 2131
Columns: 2549 entries, # mean_0_a to label
dtypes: float64(2548), object(1)
memory usage: 41.5+ MB


**Convert labels to numerical values**


In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['label'] = le.fit_transform(data['label'])

In [8]:
# count each emotion
emotion_count = data['label'].value_counts()
emotion_count

1    716
0    708
2    708
Name: label, dtype: int64

In [9]:
# 0: 'Negative'
# 1: 'Neutral'
# 2: 'Positive'

****Split the data into training and testing sets****

In [10]:
x = data.iloc[:,:-1]
y = data['label']

In [11]:
print(x.head())
print(y.head())

   # mean_0_a  mean_1_a  mean_2_a  mean_3_a  mean_4_a  mean_d_0_a  mean_d_1_a  \
0        4.62      30.3    -356.0      15.6      26.3       1.070       0.411   
1       28.80      33.1      32.0      25.8      22.8       6.550       1.680   
2        8.90      29.4    -416.0      16.7      23.7      79.900       3.360   
3       14.90      31.6    -143.0      19.8      24.3      -0.584      -0.284   
4       28.30      31.3      45.2      27.3      24.5      34.800      -5.790   

   mean_d_2_a  mean_d_3_a  mean_d_4_a  ...  fft_740_b  fft_741_b  fft_742_b  \
0      -15.70        2.06        3.15  ...       74.3       23.5       20.3   
1        2.88        3.83       -4.82  ...      130.0      -23.3      -21.8   
2       90.20       89.90        2.03  ...     -534.0      462.0     -233.0   
3        8.82        2.30       -1.97  ...     -183.0      299.0     -243.0   
4        3.06       41.40        5.52  ...      114.0       12.0       38.1   

   fft_743_b  fft_744_b  fft_745_b  ff

In [12]:

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=48)

In [13]:

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1492, 2548)
(640, 2548)
(1492,)
(640,)


# Logistic Regression


In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:


st = StandardScaler()

x_train = st.fit_transform(x_train)
x_test = st.transform(x_test)

In [16]:
model_Logistic = LogisticRegression(random_state=0)

In [17]:
model_Logistic.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [18]:
y_pred_Logistic = model_Logistic.predict(x_test)

In [19]:
y_pred_Logistic

array([1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 1, 2, 1, 2, 0, 0, 0, 2, 0,
       1, 1, 0, 1, 0, 2, 2, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 2, 1,
       1, 1, 1, 2, 0, 1, 2, 1, 2, 2, 1, 0, 0, 0, 1, 1, 0, 0, 2, 2, 2, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 2, 2, 2, 1, 0, 0, 2, 1, 0, 2, 2, 0, 1,
       0, 0, 0, 1, 1, 2, 1, 1, 1, 0, 2, 0, 0, 0, 2, 0, 1, 1, 0, 2, 0, 1,
       0, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 0, 0, 1, 0, 0, 1, 2, 2, 1,
       1, 2, 1, 2, 0, 2, 2, 0, 2, 1, 2, 2, 0, 1, 2, 1, 2, 2, 1, 0, 0, 1,
       1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 2, 0, 0, 1, 1, 1, 1, 2, 2,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 2,
       0, 1, 1, 2, 0, 2, 0, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0,
       1, 1, 2, 1, 0, 2, 1, 2, 2, 0, 1, 0, 0, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       1, 0, 0, 1, 2, 2, 2, 2, 2, 1, 1, 1, 0, 2, 2, 2, 0, 2, 0, 0, 1, 1,
       2, 2, 0, 0, 2, 2, 2, 1, 2, 0, 2, 1, 1, 0, 2, 0, 1, 1, 2, 0, 1, 2,
       0, 1, 1, 2, 0, 1, 0, 2, 0, 1, 2, 1, 0, 1, 0,

In [20]:
y_test

234     1
1316    0
1080    0
1763    0
2051    1
       ..
692     1
18      0
174     1
1176    1
1241    1
Name: label, Length: 640, dtype: int64

In [21]:
accuracy_logistic = accuracy_score(y_test, y_pred_Logistic)

In [22]:
accuracy_logistic

0.9640625

In [23]:
mse_logistic = mean_squared_error(y_test, y_pred_Logistic)

In [24]:
mse_logistic

0.1203125

# Decision Tree

In [25]:
from sklearn.tree import DecisionTreeClassifier

In [26]:
model_DecisionTree = DecisionTreeClassifier(criterion='entropy', random_state=42, max_depth=7)

In [27]:
model_DecisionTree.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=7, random_state=42)

In [28]:
y_pred_DecisionTree = model_DecisionTree.predict(x_test)

In [29]:
y_pred_DecisionTree


array([1, 0, 0, 0, 1, 2, 2, 0, 0, 0, 2, 0, 2, 1, 2, 1, 2, 0, 0, 0, 2, 0,
       1, 1, 0, 2, 0, 2, 2, 1, 2, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 2, 1,
       1, 1, 1, 2, 0, 1, 2, 1, 2, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 2, 2, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 2, 2, 1, 0, 0, 2, 1, 0, 2, 2, 0, 1,
       0, 0, 0, 1, 1, 2, 1, 1, 1, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 0, 1,
       0, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 0, 0, 1, 0, 0, 1, 2, 2, 1,
       1, 2, 1, 2, 0, 2, 2, 0, 2, 1, 2, 2, 0, 1, 2, 1, 2, 2, 1, 0, 0, 1,
       1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 1, 2, 0, 0, 1, 1, 1, 1, 2, 2,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 2,
       0, 1, 1, 2, 0, 2, 0, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0,
       1, 1, 2, 1, 0, 2, 1, 2, 0, 0, 1, 0, 0, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       1, 0, 0, 1, 2, 2, 2, 2, 2, 1, 1, 1, 0, 2, 2, 2, 0, 2, 0, 0, 1, 1,
       2, 2, 0, 0, 0, 2, 2, 1, 2, 0, 2, 1, 1, 0, 2, 0, 1, 1, 2, 0, 1, 2,
       0, 1, 1, 2, 2, 1, 0, 2, 0, 1, 2, 1, 0, 1, 0,

In [30]:
y_test


234     1
1316    0
1080    0
1763    0
2051    1
       ..
692     1
18      0
174     1
1176    1
1241    1
Name: label, Length: 640, dtype: int64

In [31]:
accuracy_DecisionTree = accuracy_score(y_test, y_pred_DecisionTree)

In [32]:
accuracy_DecisionTree


0.971875

In [33]:
mse_DecisionTree = mean_squared_error(y_test, y_pred_DecisionTree)

In [34]:
mse_DecisionTree

0.09375

# Neural Network Model

In [35]:
import tensorflow as tf

In [36]:
model_NN = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(x_train.shape[1],)),
    tf.keras.layers.Dense(256,activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(3, activation='softmax')
])

In [37]:
# compilation
model_NN.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [38]:

# Train the model
m = model_NN.fit(x_train, y_train, validation_split=0.2, epochs=70, batch_size=32)

Epoch 1/70
38/38 [==============================] - 2s 21ms/step - loss: 1.6648 - accuracy: 0.7351 - val_loss: 0.3386 - val_accuracy: 0.8896
Epoch 2/70
38/38 [==============================] - 0s 12ms/step - loss: 0.8160 - accuracy: 0.8483 - val_loss: 0.3162 - val_accuracy: 0.8997
Epoch 3/70
38/38 [==============================] - 0s 12ms/step - loss: 0.7623 - accuracy: 0.8541 - val_loss: 0.1873 - val_accuracy: 0.9331
Epoch 4/70
38/38 [==============================] - 0s 11ms/step - loss: 0.5709 - accuracy: 0.8801 - val_loss: 0.1754 - val_accuracy: 0.9130
Epoch 5/70
38/38 [==============================] - 0s 12ms/step - loss: 0.4706 - accuracy: 0.8818 - val_loss: 0.1606 - val_accuracy: 0.9331
Epoch 6/70
38/38 [==============================] - 0s 12ms/step - loss: 0.4717 - accuracy: 0.9053 - val_loss: 0.1965 - val_accuracy: 0.9398
Epoch 7/70
38/38 [==============================] - 0s 13ms/step - loss: 0.4027 - accuracy: 0.8885 - val_loss: 0.1521 - val_accuracy: 0.9398
Epoch 8/70
38

In [39]:
# model evaluation
model_acc= model_NN.evaluate(x_test, y_test)[1]
model_acc

20/20 [==============================] - 0s 3ms/step - loss: 0.4639 - accuracy: 0.9719


0.971875011920929

In [40]:
y_pred_NN = np.argmax(model_NN.predict(x_test), axis=-1)

20/20 [==============================] - 0s 3ms/step


In [41]:
# classification report
clr = classification_report(y_test, y_pred_NN, target_names={'Negative','Neutral', 'Positive'})

In [42]:
print('Classification report:\n', clr)

Classification report:
               precision    recall  f1-score   support

    Positive       0.95      0.98      0.96       205
     Neutral       0.99      1.00      0.99       224
    Negative       0.98      0.94      0.96       211

    accuracy                           0.97       640
   macro avg       0.97      0.97      0.97       640
weighted avg       0.97      0.97      0.97       640



# Random Forest

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
model_RandomForest = RandomForestClassifier(n_estimators=200, criterion="entropy")
model_RandomForest.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [45]:
y_pred_RandomForest = model_RandomForest.predict(x_test)

In [46]:

y_pred_RandomForest

array([1, 0, 0, 0, 1, 2, 2, 0, 0, 0, 2, 0, 2, 1, 2, 1, 2, 0, 0, 0, 2, 0,
       1, 1, 0, 1, 0, 2, 2, 1, 2, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 2, 1,
       1, 1, 1, 2, 0, 1, 2, 1, 2, 2, 1, 0, 0, 0, 1, 1, 0, 0, 2, 2, 2, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 2, 2, 1, 0, 0, 2, 1, 0, 2, 2, 0, 1,
       0, 0, 0, 1, 1, 2, 1, 1, 1, 0, 2, 0, 0, 0, 2, 0, 1, 2, 0, 2, 0, 1,
       0, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 0, 0, 1, 0, 0, 1, 2, 2, 1,
       1, 2, 1, 2, 0, 2, 2, 0, 2, 1, 2, 2, 0, 1, 2, 1, 2, 2, 1, 0, 0, 1,
       1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 1, 2, 0, 0, 1, 1, 1, 1, 2, 2,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 2,
       0, 1, 1, 2, 0, 2, 0, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0,
       1, 1, 2, 1, 0, 2, 1, 2, 2, 0, 1, 0, 0, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       1, 0, 0, 1, 2, 2, 2, 2, 2, 1, 1, 1, 0, 2, 2, 2, 0, 2, 0, 0, 1, 1,
       2, 2, 0, 0, 2, 2, 2, 1, 2, 0, 2, 1, 1, 2, 2, 0, 1, 1, 2, 0, 1, 2,
       0, 1, 1, 2, 0, 1, 0, 2, 0, 1, 2, 1, 0, 1, 0,

In [47]:
accuracy_RandomForest = accuracy_score(y_test, y_pred_RandomForest)

In [48]:
accuracy_RandomForest

0.9875

In [79]:
mse_RandomForest = mean_squared_error(y_test, y_pred_RandomForest)

In [80]:
mse_RandomForest

0.034375

In [49]:

cm_RandomForest = confusion_matrix(y_test, y_pred_RandomForest)

In [50]:
cm_RandomForest

array([[203,   0,   2],
       [  0, 223,   1],
       [  3,   1, 207]])

# AdaBoost -


In [51]:
from sklearn.ensemble import AdaBoostClassifier

In [52]:
adaboost_model = AdaBoostClassifier(random_state=96)

In [53]:
adaboost_model.fit(x_train, y_train)

AdaBoostClassifier(random_state=96)

In [54]:
# training score
adaboost_model.score(x_train, y_train)

0.8827077747989276

In [55]:
# Testing score
adaboost_model.score(x_test, y_test)

0.890625

In [56]:
# Hyperparameter tuning

In [57]:
adaboost_model2 = AdaBoostClassifier(random_state=96, base_estimator=RandomForestClassifier(random_state=100), n_estimators=100)

In [58]:
adaboost_model2.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


AdaBoostClassifier(base_estimator=RandomForestClassifier(random_state=100),
                   n_estimators=100, random_state=96)

In [59]:
# training score
adaboost_model2.score(x_train, y_train)

1.0

In [60]:
# testing score
adaboost_model2.score(x_test, y_test)

0.9890625

# Grid Search CV

In [61]:
data.columns

Index(['# mean_0_a', 'mean_1_a', 'mean_2_a', 'mean_3_a', 'mean_4_a',
       'mean_d_0_a', 'mean_d_1_a', 'mean_d_2_a', 'mean_d_3_a', 'mean_d_4_a',
       ...
       'fft_741_b', 'fft_742_b', 'fft_743_b', 'fft_744_b', 'fft_745_b',
       'fft_746_b', 'fft_747_b', 'fft_748_b', 'fft_749_b', 'label'],
      dtype='object', length=2549)

In [62]:
import numpy as np
from scipy import stats
df_zscore = data[(np.abs(stats.zscore(data)) < 3).all(axis=1)]

In [63]:
def remove_outliers(data,columns,n_std):
    for col in columns:
        print('Working on column: {}'.format(col))

        mean = data[col].mean()
        sd = data[col].std()

        data = data[(data[col] <= mean+(n_std*sd))]

    return data

In [64]:

columns = data.columns
n_std = 4
df_no_outliers = remove_outliers(df_zscore, columns, n_std)

Working on column: # mean_0_a
Working on column: mean_1_a
Working on column: mean_2_a
Working on column: mean_3_a
Working on column: mean_4_a
Working on column: mean_d_0_a
Working on column: mean_d_1_a
Working on column: mean_d_2_a
Working on column: mean_d_3_a
Working on column: mean_d_4_a
Working on column: mean_d_0_a2
Working on column: mean_d_1_a2
Working on column: mean_d_2_a2
Working on column: mean_d_3_a2
Working on column: mean_d_4_a2
Working on column: mean_d_5_a
Working on column: mean_d_6_a
Working on column: mean_d_7_a
Working on column: mean_d_8_a
Working on column: mean_d_9_a
Working on column: mean_d_10_a
Working on column: mean_d_11_a
Working on column: mean_d_12_a
Working on column: mean_d_13_a
Working on column: mean_d_14_a
Working on column: mean_d_15_a
Working on column: mean_d_16_a
Working on column: mean_d_17_a
Working on column: mean_d_18_a
Working on column: mean_d_19_a
Working on column: mean_d_20_a
Working on column: mean_d_21_a
Working on column: mean_d_22_a


In [65]:
df_no_outliers.shape

(73, 2549)

In [81]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

model_params = {

    'decision_tree': {
        'model': DecisionTreeClassifier(criterion='entropy', max_depth=14, random_state=0),
        'params' : {
            'max_depth': [3, 5,10,15,20,25,30]
        }
    },

    'knn': {
        'model': KNeighborsClassifier(metric = 'minkowski'),
        'params' : {
            'n_neighbors': [4,5,6,7,8,9,10]
        }
    },

    'svm': {
        'model': SVC(gamma='auto'),
        'params' : {
            'C': [1,10,15,20,25,30],
            'kernel': ['rbf','linear']
        }
    },

    'random_forest': {
        'model': RandomForestClassifier(random_state=50),
        'params' : {
            'n_estimators': [50, 100, 150, 200]
        }
    },
    'AdaBoost': {
        'model': AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=42)),
        'params': {
            'n_estimators': [1, 2, 3, 4, 5, 6]
        }
    }

}

In [78]:
from sklearn.model_selection import GridSearchCV
scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(x_train, y_train)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

data = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
print(data)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/en

           model  best_score                 best_params
0  decision_tree    0.965152            {'max_depth': 5}
1            knn    0.937665          {'n_neighbors': 5}
2            svm    0.969821  {'C': 10, 'kernel': 'rbf'}
3  random_forest    0.986593        {'n_estimators': 90}
4       AdaBoost    0.951745         {'n_estimators': 4}
